name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verify Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml pandas selenium webdriver_manager

    - name: Verify installed packages
      run: pip list

    - name: Run ceoban.py
      run: |
        echo "Running ceoban.py..."
        python ceoban.py || { echo "ceoban.py failed"; exit 1; }

    - name: Run kfc.py
      run: |
        echo "Running kfc.py..."
        python kfc.py || { echo "kfc.py failed"; exit 1; }

    - name: Run mac.py
      run: |
        echo "Running mac.py..."
        python mac.py || { echo "mac.py failed"; exit 1; }

    - name: Run lotte.py
      run: |
        echo "Running lotte.py..."
        python lotte.py || { echo "lotte.py failed"; exit 1; }

    - name: Check for JSON files
      run: |
        echo "Checking for JSON files..."
        ls -l ceoban/ceoban_*.json || echo "No ceoban JSON files found"
        ls -l lotte/lotte_*.json || echo "No lotte JSON files found"
        ls -l kfc/kfc_*.json || echo "No kfc JSON files found"
        ls -l macdonald/macdonald_*.json || echo "No macdonald JSON files found"

    - name: Commits
      run: |
        git config --global user.email "sdw10195@gmail.com"
        git config --global user.name "seodaewon1"
        
        git add ceoban/ceoban_*.json || echo "No ceoban JSON files to add"
        git add lotte/lotte_*.json || echo "No lotte JSON files to add"
        git add kfc/kfc_*.json || echo "No kfc JSON files to add"
        git add macdonald/macdonald_*.json || echo "No macdonald JSON files to add"
        
        git commit -m "차트 수집 완료" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
