name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verify Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml pandas selenium webdriver_manager

    - name: Verify installed packages
      run: pip list

    - name: Run ceoban.py
      run: |
        echo "Running ceoban.py..."
        python ceoban.py
        echo "Checking ceoban JSON files..."
        ls -l ceoban/ || echo "No ceoban directory found"
        ls -l ceoban/ceoban_*.json || echo "No ceoban JSON files found"
      continue-on-error: true

    - name: Run kfc.py
      run: |
        echo "Running kfc.py..."
        python kfc.py
        echo "Checking kfc JSON files..."
        ls -l kfc/ || echo "No kfc directory found"
        ls -l kfc/kfc_*.json || echo "No kfc JSON files found"
      continue-on-error: true

    - name: Run mac.py
      run: |
        echo "Running mac.py..."
        python mac.py
        echo "Checking macdonald JSON files..."
        ls -l macdonald/ || echo "No macdonald directory found"
        ls -l macdonald/macdonald_*.json || echo "No macdonald JSON files found"
      continue-on-error: true

    - name: Run lotte.py
      run: |
        echo "Running lotte.py..."
        python lotte.py
        echo "Checking lotte JSON files..."
        ls -l lotte/ || echo "No lotte directory found"
        ls -l lotte/lotte_*.json || echo "No lotte JSON files found"
      continue-on-error: true

    - name: Show contents of ceoban directory
      run: |
        echo "Contents of ceoban directory:"
        ls -l ceoban/

    - name: Show contents of lotte directory
      run: |
        echo "Contents of lotte directory:"
        ls -l lotte/

    - name: Show contents of kfc directory
      run: |
        echo "Contents of kfc directory:"
        ls -l kfc/

    - name: Show contents of macdonald directory
      run: |
        echo "Contents of macdonald directory:"
        ls -l macdonald/

    - name: Commit changes
      run: |
        git config --global user.email "sdw10195@gmail.com"
        git config --global user.name "seodaewon1"
        
        git add ceoban/ceoban_*.json || echo "No ceoban JSON files to add"
        git add lotte/lotte_*.json || echo "No lotte JSON files to add"
        git add kfc/kfc_*.json || echo "No kfc JSON files to add"
        git add macdonald/macdonald_*.json || echo "No macdonald JSON files to add"
        
        git commit -m "차트 수집 완료" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
